### ISSUE TITLE
[CONTENT ORGANISATION] Distinguish between different types of publications

### ISSUE THREAD

**Issue by SamHames** [QUT-Digital-Observatory/australian_digital_observatory_site#11]
Not an issue right now, but the publication list we have is currently more "Useful publications to refer to" and less "Publications that happened because of this ARDC project" - in the future we may want to add an additional list and make a distinction between the two.

The value of the former list is to keep it curated, with the aim of giving people a brief overview/tour of possibilities in the space to help them consider and plan their own projects.

**Comment by Quiet27** [comment]
@boyd-nguyen and @Quiet27 discussed this and we feel that we should just keep it as a list of publications.
