### ISSUE TITLE
[CONTENT EXPANSION] Add other publications to Publications

### ISSUE THREAD

**Issue by boyd-nguyen** [QUT-Digital-Observatory/australian_digital_observatory_site#46]
Some publications have not been uploaded. Get all of them to the site.

**Comment by Quiet27** [comment]
Refer to case for conversion for a fairly up-to-date list of publications.

**Comment by Quiet27** [comment]
Link to PR that addresses this issue: https://github.com/QUT-Digital-Observatory/australian_digital_observatory_site/pull/63
