### ISSUE TITLE
[CONTENT CREATION/UPDATE] Draft content for DO portfolio

### ISSUE THREAD

**Issue by boyd-nguyen** [QUT-Digital-Observatory/australian_digital_observatory_site#51]
- [ ] Select which projects to include
- [ ] Write a case study for each selected project

**Comment by Quiet27** [comment]
Depends on #69 being completed

**Comment by Quiet27** [comment]
Closing due to this work being captured in https://github.com/QUT-Digital-Observatory/australian_digital_observatory_site/issues/78
