### ISSUE TITLE
Minor issues with spacing in mobile view

### ISSUE THREAD

**Issue by SamHames** [QUT-Digital-Observatory/australian_digital_observatory_site#6]
This is in Firefox mobile on Android, the first view looks like the attached screenshots.

Specifically:
- the title is cut off by the edge of the screen on the right. 
- the text width for the body is too narrow to be easily readable
- the partner logos overlap and overflow

![Screenshot_20220204-151635](https://user-images.githubusercontent.com/8400977/152476324-7c2856a2-fee5-4c8e-b7a1-4a033cedfb2c.png)
![Screenshot_20220204-151625](https://user-images.githubusercontent.com/8400977/152476329-f6bf158f-2661-41ce-a21c-4f5ecab9c1a6.png)

**Comment by betsybookwyrm** [comment]
Fixed in #8
